### ISSUE TITLE
fix Decrypt error - first column "How you learned about NEXT" errors out DataTables, won't display in table view

### ISSUE THREAD

**Issue by kylenstone** [schuyler1d/encrypted-post#12]
```DataTables warning: table id=results - Requested unknown parameter 'Please tell us how you learned about NEXT. Be specific.' for row 0, column 0. For more information about this error, please see http://datatables.net/tn/4```

**Comment by kylenstone** [comment]
This error has shifted around a bit.  It seems like the very first field we send to dataTables causes this error.

Maybe its a problem with the decrypt.js code, we're not mapping the first row correctly, its getting confused with a header or something?

**Comment by schuyler1d** [comment]
This was annoyingly about having periods (.) in the field name.  I work around that by replacing them in semi-colons, but it might also be good to change the field names not to match exactly the question so if we tweak the wording of the question, the answers can stay in the same column.
